### ISSUE TITLE
Tokenizer not available error

### ISSUE THREAD

**Issue by RichardScottOZ** [davendw49/k2#8]
```python
transformers) ubuntu@:~/data/k2$ python -m apply_delta --base-model-path decapoda-research/llama-7b-hf --target-model-path /home/ubuntu/geollama/ --delta-path daven3/k2_fp_delta
Loading the delta weights from daven3/k2_fp_delta
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/transformers/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/anaconda3/envs/transformers/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/data/k2/apply_delta.py", line 165, in <module>
    apply_delta(args.base_model_path, args.target_model_path, args.delta_path)
  File "/home/ubuntu/data/k2/apply_delta.py", line 127, in apply_delta
    delta_tokenizer = AutoTokenizer.from_pretrained(delta_path, use_fast=False)
  File "/home/ubuntu/anaconda3/envs/transformers/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 720, in from_pretrained
    return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/ubuntu/anaconda3/envs/transformers/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1825, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'daven3/k2_fp_delta'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'daven3/k2_fp_delta' is the correct path to a directory containing all relevant files for a LlamaTokenizerFast tokenizer.
```

Now because you have a different sort of model it can't find a tokenizer from the pathname perhaps - do you actually have this available you could upload?

**Comment by davendw49** [comment]
Hi, Richard, thanks for your kind reminding. We didn't upload the tokenizer for the delta model, since it share the same tokenizer as the original Llama, therefore, the code of `apply_delta.py` in [line 127](https://github.com/davendw49/k2/blob/4e7c2ecf62a7247c05cbfd1fe92769500073c7fb/apply_delta.py#L127) should be changed as follows.
```python
delta_tokenizer = AutoTokenizer.from_pretrained(base_model_path, use_fast=False)
```

**Comment by RichardScottOZ** [comment]
Ok - speed there - is the original Llama tokenizer going to be looking for the LlamaTokenizer class though?

**Comment by davendw49** [comment]
Yes, but `AutoTokenizer` also works.
